### ISSUE TITLE
Center the logo in the header

### ISSUE THREAD

**Issue by alexanderfanden** [SiamKreative/alex-portfolio#12]
Now the logo is not perfectly centered, since it's evenly distributed inbetween the menu items (and the left menu is wider than the right)

![image](https://user-images.githubusercontent.com/7322127/48964813-3378c400-efe2-11e8-9677-3db9622d54cc.png)

**Comment by SiamKreative** [comment]
I would prefer a CSS only solution than using JS to get element width (159133f)
